<?php
declare(strict_types=1);
require dirname(__DIR__) . '/auth.php';
require_once dirname(__DIR__) . '/admin-nav.php';
if (!jg_admin_is_authenticated()) { header('Location: ../dashboard/?view=overview'); exit; }
$adminCss=(string)@filemtime(dirname(__DIR__).'/admin.css');$pageCss=(string)@filemtime(__DIR__.'/partner-stock-orders.css');$pageJs=(string)@filemtime(dirname(__DIR__).'/partner-stock-orders.js');
?>
<!DOCTYPE html><html lang="en" data-admin-theme="dark"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Class B Operations | Executive Dashboard</title><meta name="robots" content="noindex,nofollow"><?php render_admin_initial_theme_script(); ?><?php render_admin_favicons('partner-profiles'); ?><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap"><link rel="stylesheet" href="../admin.css?v=<?php echo urlencode($adminCss?:'1'); ?>"><link rel="stylesheet" href="partner-stock-orders.css?v=<?php echo urlencode($pageCss?:'1'); ?>"></head>
<body class="admin-body is-dashboard"><div class="admin-app admin-app-suite ps-app" data-partner-stock data-endpoint="../api/partner-stock/"><div class="admin-backdrop admin-backdrop-a"></div><div class="admin-shell"><?php render_admin_sidebar('partner'); ?><div class="admin-shell-main"><header class="admin-topbar"><div class="admin-topbar-brand"><span class="admin-chip">Partner · Class B</span><h1>Stock Operations</h1></div><?php render_admin_topbar_actions(); ?></header>
<main class="ps-main"><section class="ps-heading"><div><a href="../partner-profiles/" class="ps-back"><svg viewBox="0 0 24 24"><path d="m15 18-6-6 6-6"/></svg>Partner profiles</a><h2>Class B orders and balances</h2><p>Verify deposits, prepare shipping, and retain a complete operational record.</p></div><div class="ps-live"><i></i><span>Shared partner ledger</span></div></section>
<section class="ps-metrics"><article><span class="is-amber"><svg viewBox="0 0 24 24"><path d="M12 2v4M12 18v4M4.9 4.9l2.8 2.8M16.3 16.3l2.8 2.8M2 12h4M18 12h4"/></svg></span><div><small>Deposits to review</small><strong data-metric-deposits>0</strong></div></article><article><span class="is-blue"><svg viewBox="0 0 24 24"><path d="M10 17h4V5H2v12h3M14 9h4l4 4v4h-3M8 20a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM16 20a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/></svg></span><div><small>Shipments to arrange</small><strong data-metric-orders>0</strong></div></article><article><span class="is-green"><svg viewBox="0 0 24 24"><path d="m6 12 4 4 8-8"/><circle cx="12" cy="12" r="9"/></svg></span><div><small>Active at Store Ops</small><strong data-metric-store>0</strong></div></article><article><span><svg viewBox="0 0 24 24"><path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5M16 13h2"/></svg></span><div><small>Partner balances</small><strong data-metric-balance>Rp0</strong></div></article></section>
<section class="ps-workspace"><header class="ps-toolbar"><div class="ps-tabs"><button type="button" class="is-active" data-tab="orders"><svg viewBox="0 0 24 24"><path d="m7.5 4.27 9 5.15M21 8l-9 5-9-5M12 22V12"/></svg>Shipment orders <i data-tab-order-count>0</i></button><button type="button" data-tab="deposits"><svg viewBox="0 0 24 24"><path d="M12 19V5M5 12l7-7 7 7"/></svg>Balance requests <i data-tab-deposit-count>0</i></button><button type="button" data-tab="wallets"><svg viewBox="0 0 24 24"><path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5M16 13h2"/></svg>Balances</button></div><label class="ps-search"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m16 16 4 4"/></svg><input type="search" placeholder="Search partner, order, SKU or recipient" data-search></label></header>
<div class="ps-body"><section class="ps-list"><div class="ps-list-head"><span data-list-title>Shipment orders</span><div class="ps-segments" data-order-filters><button type="button" class="is-active" data-filter="all">All</button><button type="button" data-filter="attention">Needs action</button><button type="button" data-filter="store">Store Ops</button><button type="button" data-filter="done">Done</button></div></div><div data-list><div class="ps-loading"><span></span>Loading Class B operations…</div></div></section><aside class="ps-detail" data-detail><div class="ps-detail-empty"><svg viewBox="0 0 24 24"><path d="m7.5 4.27 9 5.15M21 8l-9 5-9-5M12 22V12"/></svg><strong>Select a record</strong><p>Its products, contact details, files, and timeline will appear here.</p></div></aside></div></section></main></div></div><?php render_admin_notification_drawer(); ?><?php render_admin_chrome_script(); ?></div><div class="ps-toast" data-toast hidden><svg viewBox="0 0 24 24"><path d="m6 12 4 4 8-8"/></svg><span></span></div><script type="module" src="../partner-admin.js?v=<?php echo urlencode((string)@filemtime(dirname(__DIR__).'/partner-admin.js')); ?>"></script><script type="module" src="../partner-stock-orders.js?v=<?php echo urlencode($pageJs?:'1'); ?>"></script></body></html>
