<?php

return [
    // Example only. Do not edit this file on the server because Git deploys will overwrite it.
    // Put real credentials in config.local.php or /public_html/config.local.php instead.
    'db_host' => 'localhost',
    'db_port' => '3306',
    'db_name' => 'u558678012_Bign',
    'db_user' => 'your_db_user',
    'db_password' => 'your_db_password',
    'db_charset' => 'utf8mb4',
];
