<?php
declare(strict_types=1);
namespace JenangMcp;
function tableTools(): array {
    $str=['type'=>'string'];$names=['catalog','sales_lines','sales_orders',...array_keys(tableRegistry())];
    $base=['annotations'=>['readOnlyHint'=>true,'destructiveHint'=>false,'idempotentHint'=>true,'openWorldHint'=>false],'securitySchemes'=>[['type'=>'oauth2','scopes'=>[TABLE_SCOPE]]],'_meta'=>['securitySchemes'=>[['type'=>'oauth2','scopes'=>[TABLE_SCOPE]]]],'outputSchema'=>['type'=>'object','properties'=>['data'=>['type'=>'object']],'required'=>['data']]];
    $table=['type'=>'string','enum'=>$names];
    $arr=fn($item,$max=20)=>['type'=>'array','items'=>$item,'maxItems'=>$max];
    $filter=['type'=>'object','properties'=>['column'=>$str,'operator'=>['type'=>'string','enum'=>['eq','ne','gt','gte','lt','lte','in','is_null','not_null']],'value'=>['anyOf'=>[['type'=>'string'],['type'=>'number'],['type'=>'integer'],['type'=>'array','items'=>['anyOf'=>[['type'=>'string'],['type'=>'number'],['type'=>'integer']]],'minItems'=>1,'maxItems'=>100],['type'=>'null']]]],'required'=>['column','operator'],'additionalProperties'=>false];
    $metric=['type'=>'object','properties'=>['function'=>['type'=>'string','enum'=>['count','count_distinct','sum','min','max','avg']],'column'=>$str,'as'=>['type'=>'string','pattern'=>'^[a-z][a-z0-9_]{0,39}$']],'required'=>['function','as'],'additionalProperties'=>false];
    $order=['type'=>'object','properties'=>['column'=>$str,'direction'=>['type'=>'string','enum'=>['asc','desc']]],'required'=>['column'],'additionalProperties'=>false];
    return [
        $base+['name'=>'jg_list_tables','title'=>'Discover dashboard data tables','description'=>'List reviewed business views covering all approved dashboard families, their sources and aggregate-only restrictions. Availability is verified when queried; never assumes all source-schema tables exist live.','inputSchema'=>['type'=>'object','properties'=>(object)[],'additionalProperties'=>false]],
        $base+['name'=>'jg_describe_table','title'=>'Describe dashboard table','description'=>'Show exact typed columns, record grain, date basis and metric cautions before querying. Customer contacts, credentials and free-text notes are excluded. Datetime filters use UTC; _jakarta_day/_jakarta_month dimensions convert supported timestamp fields to Jakarta.','inputSchema'=>['type'=>'object','properties'=>['table'=>$table],'required'=>['table'],'additionalProperties'=>false]],
        $base+['name'=>'jg_query_table','title'=>'Query dashboard business data','description'=>'General typed rows or filtered/grouped aggregates. Discover and describe first. Use catalog filters volume+unit for all5ml products, flavor for allPlain sizes; group sales_lines by product/flavor/volume/unit/brand/channel. For sales_lines/sales_orders, explicitly choose partner_date_basis recorded_at for UTC recording-time reports; default order_time has unverified historical local-input timezone. Other sources and physical fields retain existing date semantics. Explicit inclusive Jakarta dates required for semantic sales views, max366days. sales_orders.seller_revenue is recorded order revenue once; sales_lines.line_revenue is product-line revenue. Never sum dashboard_order_mirror.order_net_revenue. Money is decimal IDR strings. Stock, accounting, wallet, partner, ads and website tables expose stored records with explicit status/void filters. Customer activity aggregates are event counts, not identifiable or distinct customers. Paginate using next_offset; pages can change between calls. No arbitrary SQL, refresh or writes. Unavailable sources have sanitized diagnostics; available-source aggregates are explicitly observed partial subtotals, never full totals or zero for missing sources. Consolidated stored channel records are not audited all-business revenue; synchronization/deduplication limitations must accompany totals.','inputSchema'=>['type'=>'object','properties'=>['table'=>$table,'columns'=>$arr($str),'filters'=>$arr($filter),'group_by'=>$arr($str),'metrics'=>$arr($metric),'order_by'=>$arr($order,10),'limit'=>['type'=>'integer','minimum'=>1,'maximum'=>200],'offset'=>['type'=>'integer','minimum'=>0,'maximum'=>100000],'start_date'=>['type'=>'string','pattern'=>'^\\d{4}-\\d{2}-\\d{2}$'],'end_date'=>['type'=>'string','pattern'=>'^\\d{4}-\\d{2}-\\d{2}$'],'partner_date_basis'=>['type'=>'string','enum'=>['order_time','recorded_at'],'default'=>'order_time','description'=>'Partner dates only: recorded_at uses created_at UTC recording time; order_time retains order_timestamp/created_at assumed UTC, with unverified historical local-input timezone. Other source dates stay unchanged.']],'required'=>['table'],'additionalProperties'=>false]],
        $base+['name'=>'jg_annualize_sales','title'=>'Annualize observed sales revenue','description'=>'Calculate monetary recorded seller-sales run rate for explicit YYYY-MM, across marketplace, paid website, direct/counter and partner sources. Optional partner_date_basis recorded_at dates partner orders by created_at UTC recording time; default order_time assumes unverified historical event timestamps UTC. Report the selected basis and date provenance. completed_days default returns insufficient_completed_history on the first day; elapsed_time explicitly includes the partial day. Never uses units or a single product as a monetary proxy. Returns actual observed IDR, cutoff, elapsed/year seconds and provenance. Mechanical run rate is not actual annual revenue, cash, profit, forecast or audited all-business revenue; report unverified sync and cross-channel duplication. All required sources must be available for annualization; otherwise return a partial observed subtotal with null annualization and error status.','inputSchema'=>['type'=>'object','properties'=>['month'=>['type'=>'string','pattern'=>'^\\d{4}-(0[1-9]|1[0-2])$'],'basis'=>['type'=>'string','enum'=>['completed_days','elapsed_time']],'partner_date_basis'=>['type'=>'string','enum'=>['order_time','recorded_at'],'default'=>'order_time','description'=>'Partner dates only: recorded_at uses created_at UTC recording time; order_time retains order_timestamp/created_at assumed UTC, with unverified historical local-input timezone. Other source dates stay unchanged.']],'required'=>['month'],'additionalProperties'=>false]]
    ];
}
