<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require __DIR__.'/../lib/rpc.php';
require __DIR__.'/../lib/oauth.php';
use function JenangMcp\{listTables,tableDefinition,tableQuerySpec,compileTableQuery,queryTable,financialRows,annualizeSales,tools,validateAuthorization,issueCode,exchange,authenticate,revoke,allowedScopes};
$n=0;
function ok(bool $v,string $label):void{global $n;if(!$v)throw new RuntimeException($label);$n++;}
function bad(callable $f,string $label):void{try{$f();}catch(Throwable){ok(true,$label);return;}ok(false,$label);}
$c=['enabled'=>true,'table_access_approved'=>true,'table_families'=>JenangMcp\TABLE_FAMILIES,'_actor_scope'=>JenangMcp\TABLE_SCOPE,'brands'=>['ZERO'],'accounts'=>['zero-shopee'],'partners'=>[],'catalog_source'=>'passive_lookup_cache','subject'=>'fixture','client_id'=>'fixture','base_url'=>'https://admin.jenanggemi.com','redirect_uri'=>'https://chatgpt.com/connector_platform_oauth_redirect','revocation_epoch'=>0];
$dir=sys_get_temp_dir().'/jg-table-test-'.bin2hex(random_bytes(6));mkdir($dir,0700);$c['state_file']=$dir.'/state.json';
$lookup=[];foreach([['A','Drops 4X','Plain',5,'ZERO'],['B','Drops 4X','Plain',10,'ZERO'],['C','Syrup','Mint',5,'ZERO'],['D','Syrup','Plain',30,'Jenang Gemi']] as [$sku,$product,$flavor,$vol,$brand])$lookup[$sku]=['sku'=>$sku,'tag'=>'tag-'.$sku,'brand_name'=>$brand,'base_product_name'=>$product,'product_key'=>$product,'flavor_name'=>$flavor,'volume'=>$vol,'unit_name'=>'ml'];
$c['_catalog_snapshot']=['saved_at'=>'2026-10-01T00:00:00Z','lookup'=>$lookup];
ok(count(listTables($c)['tables'])===61,'61 business/semantic views');ok(count(tools($c))===7,'7 tools for dashboard scope');ok(count(tools($c+[]))===7,'persistent config bound scope');$old=$c;$old['_actor_scope']=JenangMcp\SCOPE;ok(count(tools($old))===3,'old grant remains narrow');bad(fn()=>listTables($old),'old grant denied tables');$disabled=$c;$disabled['table_access_approved']=false;bad(fn()=>listTables($disabled),'disabled denied');
$r=queryTable($c,['table'=>'catalog','filters'=>[['column'=>'volume','operator'=>'eq','value'=>5],['column'=>'unit','operator'=>'eq','value'=>'ml']]]);ok(array_column($r['data']['rows'],'sku')===['A','C'],'all5ml allproducts');
$r=queryTable($c,['table'=>'catalog','filters'=>[['column'=>'flavor','operator'=>'eq','value'=>'Plain']]]);ok(array_column($r['data']['rows'],'sku')===['A','B','D'],'allPlain acrossbrands/sizes');
$r=queryTable($c,['table'=>'catalog','filters'=>[['column'=>'product','operator'=>'eq','value'=>'Drops 4X'],['column'=>'volume','operator'=>'eq','value'=>'10'],['column'=>'unit','operator'=>'eq','value'=>'ml'],['column'=>'flavor','operator'=>'eq','value'=>'Plain']]]);ok(array_column($r['data']['rows'],'sku')===['B'],'product+size+flavor');
$r=queryTable($c,['table'=>'catalog','limit'=>1]);ok($r['pagination']['has_more']&&$r['pagination']['next_offset']===1,'explicit page continuation');$next=queryTable($c,['table'=>'catalog','limit'=>1,'offset'=>1]);ok($next['data']['rows'][0]['sku']==='B','page2');
foreach(['analytics_ip_exclusions','zero_blog_preview_links','sku_meta','accounting_receipt_files','table;DROP'] as $name)bad(fn()=>tableDefinition($name),'protected table '.$name);
foreach(['phone','raw_json','customer_name','password_hash','email','notes','receipt_url','amount; DROP'] as $col)bad(fn()=>tableQuerySpec(['table'=>'accounting_transactions','columns'=>[$col]]),'protected field '.$col);
bad(fn()=>tableQuerySpec(['table'=>'customer_activity']),'customer row query denied');bad(fn()=>tableQuerySpec(['table'=>'catalog','sql'=>'DROP']),'raw SQL denied');bad(fn()=>tableQuerySpec(['table'=>'catalog','filters'=>[['column'=>'sku','operator'=>'regex','value'=>'x']]]),'arbitrary operator');bad(fn()=>tableQuerySpec(['table'=>'catalog','limit'=>201]),'limit bound');bad(fn()=>tableQuerySpec(['table'=>'catalog','offset'=>100001]),'offset bound');
bad(fn()=>tableQuerySpec(['table'=>'dashboard_order_mirror','metrics'=>[['function'=>'sum','column'=>'order_net_revenue','as'=>'revenue_total']]]),'repeated order money cannot sum');
$s=tableQuerySpec(['table'=>'accounting_transactions','filters'=>[['column'=>'status','operator'=>'eq','value'=>"posted' OR 1=1 --"],['column'=>'amount','operator'=>'gte','value'=>100]],'group_by'=>['brand','channel'],'metrics'=>[['function'=>'sum','column'=>'amount','as'=>'amount_total']],'order_by'=>[['column'=>'amount_total','direction'=>'desc']]]);$sql=compileTableQuery($s);ok(!str_contains($sql['sql'],'OR 1=1')&&$sql['args'][0]==="posted' OR 1=1 --",'injection only parameter');ok(str_contains($sql['sql'],'GROUP BY `brand`,`channel`'),'group entire dataset before pagination');
$s=tableQuerySpec(['table'=>'customer_activity','group_by'=>['occurred_at_jakarta_day','site_key'],'metrics'=>[['function'=>'count','as'=>'events']]]);$sql=compileTableQuery($s);ok(str_contains($sql['sql'],'INTERVAL 7 HOUR')&&!str_contains($sql['sql'],'customer_name'),'aggregate UTCtoWIB without contact fields');
$base=['channel'=>'shopee','account'=>'zero-shopee','order_id'=>'o1','sku'=>'A','status'=>'COMPLETED','funds_release_status'=>'','quantity'=>2,'is_free_gift'=>0,'line_revenue'=>'12.34','order_revenue'=>'30.00','sale_at'=>'2026-09-30 18:00:00','updated_at'=>'2026-10-01 01:00:00'];
$fixtures=['marketplace'=>[$base+['line_id'=>'1'],array_replace($base,['line_id'=>'2','sku'=>'B','quantity'=>1,'line_revenue'=>'17.66']),array_replace($base,['line_id'=>'3','order_id'=>'cancelled','status'=>'REFUNDED','order_revenue'=>'999999.00'])],'website'=>[array_replace($base,['channel'=>'zero_website','account'=>'zero_website','order_id'=>'w1','line_id'=>'w1','sku'=>'C','quantity'=>3,'line_revenue'=>'10.00','order_revenue'=>'10.00'])],'direct'=>[array_replace($base,['channel'=>'walk_in','account'=>'counter','order_id'=>'d1','line_id'=>'d1','sku'=>'D','quantity'=>1,'line_revenue'=>'20.00','order_revenue'=>'20.00','payment_status'=>'unpaid'])],'partner'=>[['channel'=>'partner','account'=>'P','order_id'=>'p1','status'=>'OPEN','sku'=>'A','quantity'=>2,'order_revenue'=>'40.00','items_json'=>'[{"sku_code":"A","quantity":2,"unit_revenue":"20.00","customer_phone":"DO_NOT_RETURN"}]','sale_at'=>'2026-09-30 18:00:00','updated_at'=>'2026-10-01 01:00:00']]];
$fetch=fn($source,$p)=>$fixtures[$source];$dates=['start_date'=>'2026-10-01','end_date'=>'2026-10-01'];
$r=queryTable($c,['table'=>'sales_orders',...$dates,'metrics'=>[['function'=>'sum','column'=>'seller_revenue','as'=>'total_revenue'],['function'=>'sum','column'=>'units','as'=>'total_units'],['function'=>'count','as'=>'order_count']]],null,$fetch);$row=$r['data']['rows'][0];ok($row['total_revenue']==='100.00','all source actualmoney onceperorder');ok($row['total_units']===9&&$row['order_count']===4,'units/orders separate');ok(!str_contains(json_encode($r),'DO_NOT_RETURN'),'raw partner payload discarded');ok($r['provenance']['business_consolidation_verified']===false,'not audited business total');
$r=queryTable($c,['table'=>'sales_lines',...$dates,'filters'=>[['column'=>'volume','operator'=>'eq','value'=>5],['column'=>'unit','operator'=>'eq','value'=>'ml']],'group_by'=>['product','flavor','volume','unit'],'metrics'=>[['function'=>'sum','column'=>'units','as'=>'sold_units'],['function'=>'sum','column'=>'line_revenue','as'=>'recorded_revenue']]],null,$fetch);ok(count($r['data']['rows'])===2,'all5ml sales acrossproducts');ok($r['data']['rows'][0]['recorded_revenue']==='52.34','line revenue stays exactcents');
$now=new DateTimeImmutable('2026-10-01T12:00:00+07:00');$a=annualizeSales($c,['month'=>'2026-10'],null,$fetch,$now);ok($a['data']['status']==='insufficient_completed_history'&&$a['data']['annualized_sales_revenue']===null,'Oct1 no completedday notzero');$a=annualizeSales($c,['month'=>'2026-10','basis'=>'elapsed_time'],null,$fetch,$now);ok($a['data']['actual_observed_sales_revenue']==='100.00'&&$a['data']['annualized_sales_revenue']==='73000.00','Oct revenuebased elapsedtime annualization');ok($a['data']['elapsed_seconds']===43200,'WIB cutoff accurate');
bad(fn()=>queryTable($c,['table'=>'sales_orders',...$dates],null,function($src,$p)use($fixtures){if($src==='partner')throw new RuntimeException('fixture outage');return $fixtures[$src];}),'missing source no partial zero money');
bad(fn()=>financialRows($c,fn($src,$p)=>$src==='marketplace'?[$base+['line_id'=>'x'],$base+['line_id'=>'x']]:[],JenangMcp\period($dates)),'duplicates rejected');
foreach(JenangMcp\tableRegistry() as $name=>$d){foreach(array_keys($d['columns']) as $field)ok(!preg_match('/password|token|secret|phone|email|address|customer|raw_json|notes|proof|receipt_url/',$field),'protected projection '.$name.'.'.$field);$spec=tableQuerySpec(['table'=>$name,'metrics'=>[['function'=>'count','as'=>'records']]]);$q=compileTableQuery($spec);ok(str_starts_with($q['sql'],'SELECT ')&&!str_contains($q['sql'],';'),'registry safeSQL '.$name);}
$q=['client_id'=>$c['client_id'],'redirect_uri'=>$c['redirect_uri'],'resource'=>JenangMcp\resource($c),'response_type'=>'code','code_challenge'=>rtrim(strtr(base64_encode(hash('sha256',str_repeat('a',43),true)),'+/','-_'),'='),'code_challenge_method'=>'S256','state'=>'fixture','scope'=>JenangMcp\TABLE_SCOPE];$code=issueCode($c,$q);$x=exchange($c,['grant_type'=>'authorization_code','client_id'=>$c['client_id'],'resource'=>$q['resource'],'redirect_uri'=>$q['redirect_uri'],'code'=>$code,'code_verifier'=>str_repeat('a',43)]);ok($x['scope']===JenangMcp\TABLE_SCOPE,'freshconsent boundbroad scope');ok(authenticate($c,$x['access_token'])['scope']===JenangMcp\TABLE_SCOPE,'authenticate scope');ok(authenticate($disabled,$x['access_token'])===null,'disabled broadtoken denied');bad(fn()=>validateAuthorization($disabled,$q),'cannot request broad scope whiledisabled');
$x2=exchange($c,['grant_type'=>'refresh_token','client_id'=>$c['client_id'],'resource'=>$q['resource'],'refresh_token'=>$x['refresh_token'],'scope'=>JenangMcp\SCOPE]);ok($x2['error']==='invalid_grant','scope cannot silently alter on refresh');revoke($c,$x['access_token']);ok(authenticate($c,$x['access_token'])===null,'broad revoke');
foreach(glob($dir.'/*') as $f)unlink($f);rmdir($dir);echo json_encode(['checks'=>$n,'all5ml'=>true,'allPlain'=>true,'product_size_flavor'=>true,'observed_money'=>'100.00','annualized_money'=>'73000.00','fixtures_only'=>true])."\n";
